# Generated by Django 5.0.6 on 2024-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_medicalproduct_available_medicalproduct_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalproduct',
            name='photo',
            field=models.ImageField(upload_to='med_photos/'),
        ),
    ]
