# Generated by Django 5.0.6 on 2024-07-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
